# Generated by Django 3.1.7 on 2021-03-25 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210324_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_game',
            name='away_home',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AddField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(
                2021, 3, 25, 15, 51, 9, 325934)),
        ),
        migrations.AddField(
            model_name='player_game',
            name='dnp',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='player_game',
            name='game_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player_game',
            name='game_score',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player_game',
            name='opponent_id',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='stats.team'),
        ),
        migrations.AddField(
            model_name='player_game',
            name='plus_minus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player_game',
            name='result',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AddField(
            model_name='player_game',
            name='started',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='player_game',
            name='team_id',
            field=models.ForeignKey(
                default='', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='stats.team'),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='age',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='player_game',
            unique_together={('player_id', 'date')},
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='effective_fg_pct',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='games',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='games_started',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='league',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='season',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='two_pts',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='two_pts_attempted',
        ),
        migrations.RemoveField(
            model_name='player_game',
            name='two_pts_pct',
        ),
    ]
