# Generated by Django 3.1.7 on 2021-03-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='model_type',
            field=models.CharField(default='player', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='model_type',
            field=models.CharField(default='team', max_length=50),
        ),
    ]
