# Generated by Django 3.1.7 on 2021-03-25 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210325_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_game',
            name='season',
            field=models.CharField(default='0000-00', max_length=7),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(
                2021, 3, 25, 19, 21, 24, 995617)),
        ),
    ]
