# Generated by Django 3.1.7 on 2021-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210317_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='effective_fg_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
