# Generated by Django 3.1.7 on 2021-03-31 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20210325_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(
                2021, 3, 31, 17, 59, 40, 632599)),
        ),
    ]
