# Generated by Django 3.1.7 on 2021-03-31 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20210331_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_game',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise_id',
            field=models.CharField(
                max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(
                2021, 3, 31, 18, 10, 55, 98544)),
        ),
    ]
