# Generated by Django 3.1.7 on 2021-03-31 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20210331_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchise_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 18, 12, 56, 110333)),
        ),
    ]
