# Generated by Django 3.1.7 on 2021-03-31 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20210331_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 18, 26, 31, 148438)),
        ),
    ]
