# Generated by Django 3.1.7 on 2021-04-07 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20210331_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 14, 33, 43, 819928)),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stats.player'),
        ),
    ]
