# Generated by Django 2.2.12 on 2021-05-23 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20210407_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='csv_endpoint',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 21, 25, 34, 724791)),
        ),
    ]
